<div class="ecmCenterPane">
	<!--  Please add your configuration pane -->
	<!--  For example
    <div data-dojo-type="idx/layout/BorderContainer" data-dojo-props="gutters:true">
		<div data-dojo-attach-point="topPane" data-dojo-type="dijit/layout/ContentPane" 
				data-dojo-props="splitter:true,region:'top'">
		</div>
		<div data-dojo-attach-point="centerPane" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'center'">
		</div>
	</div>
    -->
</div>